#!/bin/bash

set -xeo pipefail
qemu-system-x86_64 --version || {
    apt update
    apt install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager
    # systemctl start libvirtd
    # systemctl enable libvirtd
    # usermod -aG libvirt $(whoami)
    # usermod -aG kvm $(whoami)
    # newgrp libvirt
}
packer version || {
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    apt update && apt install packer -y
    packer init .
}
stat output-windows-1708535165/ || ./build-windows-base
mkdir -p output-windows-1708535165
cp output-windows/packer-windows output-windows-1708535165/packer-windows
# ./build-windows-development-environment

