#!/bin/bash

set -xeo pipefail

export DISPLAY=:10.0
rm -rf output-windows-development-environment || true
PACKER_LOG=1 packer build -var "test_path=C:\\Users\\vagrant\\Desktop\\done" ./windows-development-environment.pkr.hcl 2>&1 | tee packer.log

