#!/bin/bash

set -xeo pipefail
qemu-system-x86_64 --version || {
    apt update
    apt install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager
    # systemctl start libvirtd
    # systemctl enable libvirtd
    # usermod -aG libvirt $(whoami)
    # usermod -aG kvm $(whoami)
    # newgrp libvirt
}
packer version || {
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    apt update && apt install packer -y
    packer init .
}
stat NODES || ./pic list-nodename /root/id_rsa > NODES

cat NODES | awk '{print $1}'

NODES=$(cat NODES | awk '{print $1}')
for node in $NODES; do
  echo "Node: $node"
  WINDOWS_ISO="/root/windows.iso"
  stat $WINDOWS_ISO && break || echo "windows.iso not found on $node"
  scp -i /root/id_rsa $WINDOWS_ISO $node:$WINDOWS_ISO || echo "Failed to copy windows.iso to $node"
  scp -i /root/id_rsa $node:$WINDOWS_ISO $WINDOWS_ISO || echo "Failed to copy windows.iso from $node"
done

stat output-windows/ && exit 1 || true
PACKER_LOG=1 packer build ./windows-2022.pkr.hcl 2>&1 | tee packer.log
cp -r output-windows output-windows-1708535165
qemu-system-x86_64 -m 16384 -cpu host \
  -hda output-windows-1708535165/packer-windows \
  -enable-kvm \
  -spice port=5900 \
  -display gtk \
  2>&1 | tee qemu.log

./build-windows-development-environment

