#!/bin/bash

set -xeo pipefail

curl https://raw.githubusercontent.com/qtvhao/picloud/main/pic -o pic && chmod +x pic
packer version || {
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    apt update && apt install packer -y
    packer init .
}

export DISPLAY=":10"
stat /root/.config/packer/plugins || packer init .

stat NODES || ./pic list-nodename /root/id_rsa > NODES

cat NODES | awk '{print $1}'

NODES=$(cat NODES | awk '{print $1}')
WINDOWS_ISO="/root/windows.iso"
for node in $NODES; do
  echo "Node: $node"
  stat $WINDOWS_ISO && break || echo "windows.iso not found on $node"
  scp -i /root/id_rsa $WINDOWS_ISO $node:$WINDOWS_ISO || echo "Failed to copy windows.iso to $node"
  scp -i /root/id_rsa $node:$WINDOWS_ISO $WINDOWS_ISO || echo "Failed to copy windows.iso from $node"
done

stat ./windows-installed/packer-windows-virtualbox-1708999724.ovf || \
    (PACKER_LOG=1 packer build ./windows-2022.pkr.hcl 2>&1 | tee packer.log && \
      mkdir -p ./windows-installed/ && \
      cp ./output-windows-virtualbox/* ./windows-installed/)

stat ./windows-updated/packer-windows-installed-1709014984.ovf || \
    (PACKER_LOG=1 packer build ./windows-latest.pkr.hcl 2>&1 | tee packer.log
      mkdir -p ./windows-updated/ && \
      cp ./output-windows-installed/* ./windows-updated/)

